// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: company.sql

package db

import (
	"context"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
  owner,
  headquarters,
  founded 
) VALUES (
  $1, $2, $3
)
RETURNING id, owner, headquarters, founded, created_at
`

type CreateCompanyParams struct {
	Owner        string
	Headquarters string
	Founded      int64
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Owner, arg.Headquarters, arg.Founded)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Headquarters,
		&i.Founded,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, owner, headquarters, founded, created_at FROM companies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context, id int32) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Headquarters,
		&i.Founded,
		&i.CreatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, owner, headquarters, founded, created_at FROM companies
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Headquarters,
			&i.Founded,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET headquarters = $2
WHERE id = $1
RETURNING id, owner, headquarters, founded, created_at
`

type UpdateCompanyParams struct {
	ID           int32
	Headquarters string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany, arg.ID, arg.Headquarters)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Headquarters,
		&i.Founded,
		&i.CreatedAt,
	)
	return i, err
}
