// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Company struct {
	ID           int32
	Owner        string
	Headquarters string
	Founded      int64
	CreatedAt    time.Time
}
